myparcelnl/pdk

src/Base/Factory/PdkFactory.php
src/Logger/AbstractLogger.php
src/Shipment/Collection/DefaultLogger.php
tests/Bootstrap/Config.php
tests/Bootstrap/MockLogger.php
tests/Unit/Base/Factory/PdkFactoryTest.php
tests/Unit/Logger/LoggerTest.php

feat: add logger

---

src/Base/Service/CountryService.php
src/Validation/OrderValidator.php
tests/Unit/Base/Service/CountryServiceTest.php

- add isEuCountry
- add isRowCountry
- add isUniqueCountry
- disallow null in getShippingZone

feat(service): add more methods to country service

---

config/default.php
src/Base/Concern/CurrencyServiceInterface.php
src/Base/Concern/HasPrices.php
src/Base/Concern/WeightServiceInterface.php
src/Base/Service/CurrencyService.php
src/Base/Service/WeightService.php
tests/Unit/Base/Service/CurrencyServiceTest.php
tests/Unit/Service/WeightServiceTest.php

- remove static methods from WeightService
- add WeightServiceInterface
- add CurrencyServiceInterface

feat(base): increase consistency of services

---

config/pdk-services.php
config/pdk-template.php
src/Account/Contract/AccountRepositoryInterface.php
src/Account/Repository/AbstractAccountRepository.php
src/Account/Repository/AccountRepository.php
src/Account/Service/AccountSettingsService.php
src/App/Account/Contract/PdkAccountRepositoryInterface.php
src/App/Account/Repository/AbstractPdkAccountRepository.php
src/App/Action/Backend/Account/UpdateAccountAction.php
src/Base/Factory/PdkFactory.php
src/Base/Repository/Repository.php
tests/Bootstrap/MockPdkAccountRepository.php
tests/Bootstrap/MockPdkConfig.php
tests/Unit/Repository/AbstractRepositoryMock.php

- separate AccountRepository and PdkAccountRepository
- reduce amount of api calls with invalid api keys

fix(actions): improve update account action

---

src/Frontend/Form/Builder/AbstractFormBuilderCore.php
src/Frontend/Form/Builder/AbstractFormOperationBuilder.php
src/Frontend/Form/Builder/AbstractFormSubOperationBuilder.php
src/Frontend/Form/Builder/Contract/ChainableFormOperationBuilderInterface.php
src/Frontend/Form/Builder/Contract/FormOperationInterface.php
src/Frontend/Form/Builder/Contract/FormSubOperationBuilderInterface.php
src/Frontend/Form/Builder/FormCondition.php
src/Frontend/Form/Builder/FormOperationBuilder.php
src/Frontend/Form/Builder/Operation/AbstractFormOperation.php
src/Frontend/Form/Element/AbstractPlainElement.php
src/Frontend/Form/Element/Contract/ElementBuilderInterface.php
tests/Pest.php
tests/Unit/Frontend/Form/Builder/FormConditionTest.php
tests/Unit/Frontend/Form/Builder/FormOperationBuilderTest.php

- This was not usable in the frontend

refactor(form-builder): move setValue to sub operation builder

---

config/platform/belgie.php
config/platform/myparcel.php
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(belgie)__1.json
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(belgie)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(belgie)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(myparcel)__1.json

fix(carriers): update carrier capabilities

---

src/App/Order/Calculator/General/CustomerInformationCalculator.php

Example:
```
"Notice: Indirect modification of overloaded property MyParcelNL\\Pdk\\Shipment\\Model\\Shipment::$recipient has no effect"
```

fix(orders): fix notice when billing address or recipient are not present

---

config/platform/belgie.php
config/platform/myparcel.php
src/App/Order/Calculator/General/InsuranceCalculator.php
src/Frontend/View/CarrierSettingsItemView.php
tests/Unit/App/Order/Calculator/General/CarrierSpecificCalculatorTest.php
tests/Unit/App/Order/Calculator/General/InsuranceCalculatorTest.php
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(belgie)__1.json
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(belgie)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(belgie)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(myparcel)__1.json
tests/factories/Carrier/Model/CarrierCapabilitiesFactory.php

fix(calculator): always send insurance for dpd

---

src/App/Order/Calculator/PostNl/PostNLDeliveryTypeCalculator.php
tests/Unit/App/Order/Calculator/General/CarrierSpecificCalculatorTest.php

fix(calculator): disable shipment options for postnl pickup

---

config/pdk-dependencies.php
config/pdk-template.php
src/App/Installer/Contract/InstallationMigrationInterface.php
src/App/Installer/Contract/MigrationServiceInterface.php
src/App/Installer/Contract/UpgradeMigrationInterface.php
src/App/Installer/Service/InstallerService.php
src/App/Installer/Service/MigrationService.php
src/Base/Concern/HasAttributes.php
src/Facade/Logger.php
src/Logger/AbstractLogger.php
src/Logger/Contract/PdkLoggerInterface.php
tests/Bootstrap/MockInstallationMigration100.php
tests/Bootstrap/MockLegacyMigrationService.php
tests/Bootstrap/MockMigrationService.php
tests/Bootstrap/MockPdkConfig.php
tests/Bootstrap/MockSettingsRepository.php
tests/Bootstrap/MockUpgradeMigration110.php
tests/Bootstrap/MockUpgradeMigration120.php
tests/Bootstrap/MockUpgradeMigration130.php
tests/Unit/App/Installer/Service/InstallerServiceLegacyTest.php
tests/Unit/App/Installer/Service/InstallerServiceTest.php
tests/Unit/Base/Model/ModelDeprecationTest.php
tests/Unit/Logger/LoggerTest.php

- Note: deprecations are now demoted to notice level

feat(installer): allow differentiating between migration types

---

config/schema/belgie/customs_declaration.json
config/schema/myparcel/customs_declaration.json
src/App/Order/Calculator/General/CustomsDeclarationCalculator.php
tests/Unit/App/Order/Calculator/General/CustomsDeclarationCalculatorTest.php

- applies to automatically generated customs declarations only
INT-402

fix(orders): fix customs declaration items error in row countries

---

src/App/Cart/Service/CartCalculationService.php
src/App/Order/Model/PdkProduct.php
tests/Unit/App/Cart/Service/CartCalculationServiceTest.php
tests/Unit/App/Order/Model/PdkProductTest.php

fix(checkout): honor product variant settings

---

src/App/Cart/Service/CartCalculationService.php
src/App/DeliveryOptions/Service/DeliveryOptionsService.php
src/Base/Contract/WeightServiceInterface.php
src/Base/Service/WeightService.php
tests/Unit/App/Cart/Service/CartCalculationServiceTest.php
tests/Unit/Base/Service/WeightServiceTest.php

fix(checkout): consider empty package weight

---

src/Base/Concern/HasAttributes.php
src/Base/Contract/Arrayable.php
src/Base/Model/Model.php
src/Base/Support/Utils.php
tests/Mocks/DifferentAttributeCasingModel.php
tests/Unit/Base/Model/ModelCaseConversionTest.php
tests/Unit/Base/Support/UtilsTest.php

fix(model): fix nested array keys case being changed

---

config/pdk-business-logic.php
src/Frontend/Form/Components.php
src/Frontend/View/CheckoutSettingsView.php
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_plugin_settings__1.json
tests/__snapshots__/SettingsViewTest__it_gets_settings_view_with_data_set_checkout_settings__1.json

feat(settings): add shipping methods input

---

config/schema/myparcel/order/dpd/base.json
config/schema/myparcel/order/dpd/mailbox.json
config/schema/order.json
config/validation/myparcel/order.php
src/App/DeliveryOptions/Service/DeliveryOptionsService.php
src/Validation/Validator/OrderPropertiesValidator.php
tests/__snapshots__/OrderValidatorTest__it_validates_order_with_data_set_BE_mailbox__1.json

fix(validation): improve validation for mailbox and letter

---

src/App/ShippingMethod/Model/PdkShippingMethod.php
src/Frontend/View/AbstractSettingsView.php
src/Frontend/View/CheckoutSettingsView.php
tests/Bootstrap/MockPdkShippingMethodRepository.php
tests/Unit/App/Cart/Service/CartCalculationServiceTest.php
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_plugin_settings__1.json
tests/__snapshots__/SettingsViewTest__it_gets_settings_view_with_data_set_checkout_settings__1.json
tests/factories/App/ShippingMethod/Model/PdkShippingMethodFactory.php

- Also fixed disabled shipping methods still being shown

feat(settings): allow showing description with shipping method

---

src/Account/Response/GetShopCarrierOptionsResponse.php
tests/Api/Response/ExampleGetCarrierOptionsResponse.php
tests/Integration/Features/Actions/updateAccount.feature
tests/Unit/App/Action/Backend/Account/UpdateAccountActionTest.php

fix: fix duplicate carriers when custom postnl contract is enabled

---

config/platform/myparcel.php
config/schema/myparcel/order/dpd/mailbox.json
config/validation/myparcel/order.php
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(myparcel)__1.json

feat: add support for DPD BBP

---

config/validation/myparcel/order.php
tests/Unit/Validation/ValidationTest.php

feat: add options for small package Belgium

---

src/App/Action/Backend/Webhook/CreateWebhooksAction.php
tests/Unit/App/Action/Backend/Webhook/CreateWebhooksActionTest.php

fix(webhooks): always refresh base url on regeneration of webhooks

---

config/schema/myparcel/order/dpd/base.json
src/App/Order/Calculator/Dpd/DpdCalculator.php
src/App/Order/Calculator/Dpd/DpdDeliveryDateCalculator.php
src/App/Order/Calculator/General/CarrierSpecificCalculator.php
tests/Unit/App/Order/Calculator/General/CarrierSpecificCalculatorTest.php

fix(export): allow dpd shipments

---

src/Frontend/View/CheckoutSettingsView.php
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_plugin_settings__1.json
tests/__snapshots__/SettingsViewTest__it_gets_settings_view_with_data_set_checkout_settings__1.json

feat: add default pickup view setting

---

config/platform/myparcel.php
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(myparcel)__1.json

fix: dpd shipment default insurance

---

config/schema/belgie/order/dpd/base.json

fix: resolve dpd export issue for belgium

---

config/schema/myparcel/order/postnl/base.json
config/schema/myparcel/order/postnl/be_package_pickup.json
config/schema/myparcel/order/postnl/eu_package.json
config/schema/myparcel/order/postnl/eu_package_pickup.json
config/schema/myparcel/order/postnl/nl_package.json
config/validation/myparcel/order.php
src/App/Order/Calculator/PostNl/PostNLDeliveryTypeCalculator.php
tests/Unit/App/Action/Backend/Order/ExportOrderActionTest.php
tests/__snapshots__/OrderValidatorTest__it_returns_correct_schema_with_data_set_pickup_without_location_code__1.json

feat(pickup): add postnl pickup for non nl countries

---

config/platform/myparcel.php
config/schema/myparcel/order/dhlforyou/base.json
config/schema/myparcel/order/dhlforyou/nl_package_small.json
config/validation/myparcel/order.php
src/App/Order/Calculator/DhlForYou/DhlForYouShipmentOptionsCalculator.php
tests/__snapshots__/CarrierTest__it_instantiates_carrier_from_external_identifier_with_data_set_default_carrier__1.json
tests/__snapshots__/CarrierTest__it_instantiates_carrier_from_external_identifier_with_data_set_subscription_carrier__1.json
tests/__snapshots__/CarrierTest__it_instantiates_carriers_from_name_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_gets_carriers_with_(myparcel)__1.json
tests/__snapshots__/PlatformManagerTest__it_retrieves_config_for_each_platform_with_(myparcel)__1.json

feat: allow dhlforyou pickup locations

---

src/App/Order/Calculator/General/CarrierSpecificCalculator.php
src/App/Order/Calculator/UPS/UPSCalculator.php
src/App/Order/Calculator/UPS/UPSCountryShipmentOptionsCalculator.php
tests/Unit/App/Action/Backend/Order/ExportOrderActionTest.php
tests/__snapshots__/ExportOrderActionTest__it_exports_international_orders_with_data_set_ups__data_set_default__1.json
tests/__snapshots__/ExportOrderActionTest__it_exports_international_orders_with_data_set_ups__data_set_order_mode__1.json

fix(ups): do not include delivery date for ups when exporting

---

config/schema/belgie/order/postnl/base.json
config/schema/belgie/order/postnl/nl_package.json

INT-742
Update PostNL BE base schema validation rules

fix(schema): update PostNL BE base schema validation rules

---

src/Frontend/View/CheckoutSettingsView.php
src/Settings/Model/CheckoutSettings.php
tests/__snapshots__/AbstractSettingsRepositoryTest__it_retrieves_all_categories_and_fields__1.json
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_init_script__1.json
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_plugin_settings__1.json
tests/__snapshots__/SettingsManagerTest__it_retrieves_default_settings_with_(belgie)__1.json
tests/__snapshots__/SettingsManagerTest__it_retrieves_default_settings_with_(flespakket)__1.json
tests/__snapshots__/SettingsManagerTest__it_retrieves_default_settings_with_(myparcel)__1.json
tests/__snapshots__/SettingsManagerTest__it_returns_all_keys__1.json
tests/__snapshots__/SettingsViewTest__it_gets_settings_view_with_data_set_checkout_settings__1.json

feat: add toggle for EU VAT and EORI fields in checkout settings

---

src/Carrier/Model/Carrier.php
tests/Unit/Carrier/Model/CarrierTest.php

changes fallback behaviour to not fallback to a default carrier name if an id was given
fixes INT-890

fix(carrier): fix unknown carrier ids falling back to default carrier

---

src/App/Order/Calculator/Bpost/BpostCalculator.php
src/App/Order/Calculator/Bpost/BpostDeliveryDateCalculator.php
src/App/Order/Calculator/General/CarrierSpecificCalculator.php

fix: disable delivery date selection for Bpost carrier

---

config/schema/belgie/order/bpost/base.json

fix: allow bpost pickups

---

src/Settings/Model/ProductSettings.php
src/Shipment/Model/CustomsDeclarationItem.php
src/Types/Service/TriStateService.php

fix: apply default origin country for ROW shipments

---

src/App/Order/Calculator/DhlForYou/DhlForYouDeliveryTypeCalculator.php
tests/Unit/App/Order/Calculator/DhlForYou/DhlForYouDeliveryTypeCalculatorTest.php

fix: ensure pickup location takes precedence over 'only recipient' 

---

src/App/Action/Backend/Shipment/UpdateShipmentsAction.php
src/App/Webhook/Hook/ShipmentStatusChangeWebhook.php
src/App/Webhook/PdkWebhookManager.php
src/Settings/Model/OrderSettings.php
tests/Unit/App/Webhook/Hook/ShipmentStatusChangeWebhookTest.php

fix: supply correct status setting in webhook

---

src/App/Action/Backend/Order/ExportOrderAction.php
src/App/Api/PdkEndpoint.php

feat: show api errors

---

src/Context/Model/DeliveryOptionsConfig.php
src/Frontend/View/CheckoutSettingsView.php
src/Settings/Model/CheckoutSettings.php
tests/Unit/App/Context/Model/DeliveryOptionsConfigTest.php
tests/__snapshots__/AbstractSettingsRepositoryTest__it_retrieves_all_categories_and_fields__1.json
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_delivery_options__1.json
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_init_script__1.json
tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_plugin_settings__1.json
tests/__snapshots__/SettingsManagerTest__it_retrieves_default_settings_with_(belgie)__1.json
tests/__snapshots__/SettingsManagerTest__it_retrieves_default_settings_with_(flespakket)__1.json
tests/__snapshots__/SettingsManagerTest__it_retrieves_default_settings_with_(myparcel)__1.json
tests/__snapshots__/SettingsManagerTest__it_returns_all_keys__1.json
tests/__snapshots__/SettingsViewTest__it_gets_settings_view_with_data_set_checkout_settings__1.json
tests/factories/Settings/Model/CheckoutSettingsFactory.php

feat: add pickup locations display configuration
