- Dockerfile
Hierdoor kan je dit doen:
```shell
docker compose run php composer update
```
Wat dan eenmalig de container opstart en dat commando uitvoert. Als je ENTRYPOINT gebruikt probeert hij de argumenten (`composer`, `update`) mee te geven aan het entrypoint.
> build: allow running arbitrary commands on container

- config/pdk-dependencies.php
- src/Api/Service/MyParcelApiService.php
- get composer version from json instead of a composer class for maximum compatibility
> fix(api): fix error when composer can't be used normally

- src/Shipment/Request/PostReturnShipmentsRequest.php
- tests/Unit/App/Action/Backend/Order/ExportReturnActionTest.php
- tests/__snapshots__/ExportReturnActionTest__it_exports_return_with_data_set_insurance__1.json
- tests/__snapshots__/ExportReturnActionTest__it_exports_return_with_data_set_no_return_capabilities__1.json
- tests/__snapshots__/ExportReturnActionTest__it_exports_return_with_data_set_simple_orders__1.json
> fix(returns): prevent validation error on export return

- config/pdk-settings.php
- src/App/Action/Backend/Order/UpdateOrderStatusAction.php
- tests/Unit/App/Action/Backend/Order/UpdateOrderStatusActionTest.php
> fix(order): fix error on updating order status if setting is empty

- src/App/Webhook/Hook/AbstractHook.php
- src/App/Webhook/PdkWebhookManager.php
- tests/Bootstrap/MockPdkConfig.php
- tests/Bootstrap/MockPdkWebhookManager.php
- tests/Bootstrap/TestCase.php
- tests/Unit/App/Webhook/PdkWebhookManagerTest.php
> fix(webhooks): fix order webhooks

- src/Base/Factory/PdkFactory.php
- tests/Unit/Facade/PdkTest.php
> fix(caching): use apc only when enabled

- config/pdk-default.php
- src/Context/Model/CheckoutContext.php
- tests/Bootstrap/MockLanguageService.php
- tests/__snapshots__/ContextServiceTest__it_gets_context_data_with_data_set_delivery_options_config__1.json
- tests/__snapshots__/ContextServiceTest__it_gets_context_data_with_data_set_global__1.json
- tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_delivery_options__1.json
- tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_init_script__1.json
Door [deze js-pdk commit](https://github.com/myparcelnl/js-pdk/commit/10a8a1fff644b5f6d411b9a6cbe1611fe15ce98d) worden er in de translations vanaf nu ook de delivery options vertalingen geincludeerd. Die worden hier vervolgens weer op de juiste plek in de context gestopt ✅
> feat: include delivery options translations in context

- src/App/Order/Calculator/General/InsuranceCalculator.php
- tests/Unit/App/Order/Calculator/General/InsuranceCalculatorTest.php
> fix: fix max insurance setting not being enforced

- src/Account/Response/GetShopCarrierOptionsResponse.php
- tests/Unit/App/Action/Backend/Account/UpdateAccountActionTest.php
- occurs when no custom postnl contract is present but there are still multiple enabled postnl carriers returned from the api
> fix(carriers): fix errors in another postnl carrier configuration

- src/Base/Concern/OffsetGetByPhpVersion.php
- src/Base/Concern/OffsetGetPhp7.php
- src/Base/Concern/OffsetGetPhp8.php
- src/Base/Model/Model.php
> fix: fix deprecation warning on arrayAccess::offsetGet

- composer.json
pin phpstan to v1 as v2 is not compatible with our repo yet. should fix failing checks in CI since PHPStan v2 release.
fixes INT-774
> build(phpstan): pin phpstan to v1

- src/App/Action/Backend/Shipment/UpdateShipmentsAction.php
- src/App/Order/Collection/PdkOrderCollection.php
- src/App/Order/Repository/AbstractPdkOrderRepository.php
- src/App/Webhook/Hook/ShipmentStatusChangeWebhook.php
- tests/Bootstrap/MockPdkOrderRepository.php
- tests/Unit/App/Order/Repository/AbstractPdkOrderRepositoryTest.php
- tests/Unit/App/Webhook/Hook/ShipmentStatusChangeWebhookTest.php
Allows showing shipment details including barcode in order mode, when label is printed in backoffice.
INT-627
> feat(webhooks): link shipment to order

- src/Language/Contract/LanguageServiceInterface.php
- src/Language/Service/AbstractLanguageService.php
- tests/Bootstrap/MockLanguageService.php
- tests/Unit/Language/Service/AbstractLanguageServiceTest.php
fixes INT-875, [#1252](https://github.com/myparcelnl/woocommerce/issues/1252)
> fix(language): return fallback translations even if language argument is specifically provided, and language is not supported

- composer.json
updates composer.json to not automatically install new major/breaking changes for packages when running without a lockfile
fixes INT-919
> build(deps): do not automatically upgrade to major versions

- src/App/Action/Backend/Order/UpdateOrderStatusAction.php
- src/App/Action/Backend/Shipment/UpdateShipmentsAction.php
- src/App/Webhook/Hook/ShipmentStatusChangeWebhook.php
INT-885
Since the shipment status change webhook is used for label creation from the backoffice, and the barcode is put in the order notes at that point, which is working solidly, we can safely update the order status there as well.
> fix: update order status on webhook

- config/pdk-fields.php
- src/Context/Model/CheckoutContext.php
- tests/__snapshots__/ContextServiceTest__it_gets_context_data_with_data_set_delivery_options_config__1.json
- tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_delivery_options__1.json
adds settings to the PDK checkout context to support functionality for the address widget vue package
> feat(address): add pdk settings for the address widget

- src/App/Order/Calculator/PostNl/PostNLReceiptCodeCalculator.php
- tests/Unit/App/Order/Calculator/PostNl/PostNLReceiptCodeCalculatorTest.php
> feat: allow receipt code be

- src/Frontend/View/OrderSettingsView.php
- tests/__snapshots__/FrontendRenderServiceTest__it_renders_component_with_data_set_plugin_settings__1.json
- tests/__snapshots__/SettingsViewTest__it_gets_settings_view_with_data_set_order_settings__1.json
Saving the client address in the backoffice address book is not possible in order modus. The toggle being still present confused users obviously. Removed the toggle when the option is not available.
Reference: https://developer.myparcel.nl/api-reference/14.order-object-definitions.html
INT-902
> fix(settings): remove save address option when unavailable

- src/Frontend/Form/Element/Concern/HasOptions.php
Fix crash when order status key is null due to incomplete creation in PrestaShop.
Some plugins using the PDK crashed because array_keys() returned null as a key, which caused a type error in the callback expecting a string.
This commit allows the key to be nullable and safely casts it to a string.
INT-973
> fix: fix unreachable settings page when order status is NULL

- .github/workflows/release.yml
- src/App/Action/Backend/Shipment/PrintShipmentsAction.php
- tests/Unit/App/Order/Calculator/General/LabelDescriptionCalculatorTest.php
INT-1155
This PR also updates the labeldescriptiontest to a date far in the future, to have it keep working (dates in the past are not displayed).
> fix: print more than one label on first a4 in bulk
